name: build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image for AWS
        id: docker_build_aws
        uses: docker/build-push-action@v2
        with:
          push: false
          target: kube-branch-cleaner-aws

      - name: Build docker image for bare-metal
        id: docker_build_bare_metal
        uses: docker/build-push-action@v2
        with:
          push: false
          target: kube-branch-cleaner-metal
