name: ci

on:
  push:
    tags:
      - "*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image for AWS
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          target: k8s-prune-aws
          push: true
          tags: parkside/k8s-branch-cleaner:$RELEASE_VERSION-bare-metal

      - name: Build and push docker image for bare-metal
        id: docker_build_push_bare_metal
        uses: docker/build-push-action@v2
        with:
          target: k8s-prune-bare-metal
          push: true
          tags: parkside/k8s-branch-cleaner:$RELEASE_VERSION-aws
