name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image for AWS
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          target: kube-will-hunt-aws
          push: true
          tags: |
            parkside/kube-will-hunt:${{ env.RELEASE_VERSION }}-aws
            parkside/kube-will-hunt:latest-aws

      - name: Build and push docker image for bare-metal
        id: docker_build_push_bare_metal
        uses: docker/build-push-action@v2
        with:
          target: kube-will-hunt-bare-metal
          push: true
          tags: |
            parkside/kube-will-hunt:${{ env.RELEASE_VERSION }}-bare-metal
            parkside/kube-will-hunt:latest-bare-metal
